version: "3.9"

services:
  gameap:
    image: gameap/gameap:latest
    container_name: gameap
    user: root
    ports:
      - "8025:8025"
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8025
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgres://gameap:user12das@postgres_global:5432/gameap?sslmode=disable
      ENCRYPTION_KEY: 1c3f1e89f909c50820c815c8cc9d26c342b2ac97c4335d9623eb20b154e330c6
      AUTH_SECRET: 3b9364d2305006c3fad856377400dde514a5d15553dc89953afbc887ca8c52d9
      CACHE_DRIVER: redis
      CACHE_REDIS_ADDR: redis_server:6379
      FILES_DRIVER: local
      FILES_LOCAL_BASE_PATH: /var/lib/gameap/files
      LOGGER_LEVEL: info
    volumes:
      - gameap-storage:/var/lib/gameap/files
      - gameap-certs:/app/certs
    networks:
      - internal_network
    restart: unless-stopped

volumes:
  gameap-storage:
  postgres-data:
  redis-data:

networks:
  internal_network:
    external: true
